baseurl = "https://tech.yyh-gl.dev/"
DefaultContentLanguage = "ja"
title = "Indexing my brain"
disableLanguages = []
enableRobotsTXT = true

[pagination]
pagerSize = 5

[markup]
[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["html", "json", "rss"]

[params]
readingTime = true
heroTags = ["#Backend", "#Go", "#Kotlin", "#DDD", "#Architecture"]

[params.meta]
description = "技術系ネタ中心のブログです。サーバサイドをメインとしたフルスタックエンジニアを目指しています。"
author = "yyh-gl"

[params.intro]
paragraph = "技術ネタ中心のブログです。<br>主な扱いはバックエンド技術と設計です。"

[params.intro.pic]
src = "img/main/logo.webp"
alt = "yyh-gl's icon"

[params.social]
github = "yyh-gl"
linkedin = "yyh-gl"
x = "yyh_gl"
bluesky = "yyh-gl.bsky.social"
speaker_deck = "yyh_gl"
crowdin = "yyh-gl"

[menu]
[[menu.main]]
name = "About"
identifier = "about"
url = "about/"
pre = "<i class='far fa-id-card'></i>"
weight = 2

[[menu.main]]
name = "Blog"
identifier = "blog"
url = "blog/"
pre = "<i class='far fa-newspaper'></i>"
weight = 3

[[menu.main]]
name = "Categories"
identifier = "categories"
url = "categories/"
pre = "<i class='fas fa-sitemap'></i>"
weight = 4

[[menu.main]]
name = "Stats"
identifier = "stats"
url = "stats/"
pre = "<i class='fas fa-chart-bar'></i>"
weight = 5

#  [[menu.main]]
#    name       = "Contact"
#    identifier = "contact"
#    url        = "contact/"
#    pre        = "<i class='far fa-envelope'></i>"
#    weight     = 6

[Languages]
[Languages.ja]
languageCode = "ja"
LanguageName = "Japanese"
weight = 1

#[Languages.en]
#languageCode = "en"
#LanguageName = "English"
#weight = 2

[services]
[services.googleAnalytics]
id = ''
