name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
# TODO: 時間あるときにLintエラーをすべて直して、本ステップを復活させる
#      - name: Lint
#        run: |
#          npm install textlint textlint-rule-preset-ja-technical-writing
#          $(npm bin)/textlint ./content/**
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Build
        run: hugo --minify
      
      - name: Set favicon
        run: |
          cp -r ./static/img/favicon ./public/
#          cp ./static/img/favicon/favicon.ico ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
