name: Deployment notification

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK_51 }}\
               -H 'Content-type: application/json' \
               -d "{
                 \"text\": \"技術ブログ更新完了:memo:\nCommit: [${{ github.sha }}](https://github.com/yyh-gl/tech-blog/commit/${{ github.sha }})\"
               }"
