name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: true

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: cache-npm
        
      - name: Lint
        run: |
          npm install textlint textlint-rule-preset-ja-technical-writing
          git diff --name-only HEAD~ | xargs $(npm bin)/textlint
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true

      - name: Build
        run: hugo --minify
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
