name: Deploy to GitHub Pages

on:
  push:
  workflow_dispatch:

jobs:
  review:
    name: Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: true
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm
          restore-keys: ${{ runner.os }}-npm
      - name: Lint
        run: |
          npm install textlint textlint-rule-preset-ja-technical-writing textlint-filter-rule-comments
          git diff --name-only HEAD~ | xargs $(npm bin)/textlint
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: review
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout  
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  success_notification:
    name: Success notification
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: rtCamp/action-slack-notify@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_51 }}
          SLACK_TITLE: CI Success
        if: env.WORKFLOW_CONCLUSION == 'success'

  failure_notification:
    name: Failure notification
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: rtCamp/action-slack-notify@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_51 }}
          SLACK_TITLE: CI Failure
          SLACK_COLOR: danger
        if: env.WORKFLOW_CONCLUSION == 'failure'
